### ISSUE TITLE
Contact Deletion is not performed on the server

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#1065]
**To Reproduce**
1. Connect
2. Delete an entry in the contact list
3. Disconnect and re-connect
4. The list contains the deleted entry

**Reason**
The deletion throws the exception:
```
ERROR 13:06:30,527 [saros-XMPPContactService-ContactsThread] (XMPPContactsService.java:239) Remove of XMPPContact [bareJid=testwd, baseStatus=ContactStatus [mode=SUBSCRIPTION_PENDING, message=null], bestResource=null] was not possible
bad-request(400) Possessing 'ask' attribute is not allowed by RFC6121
	at org.jivesoftware.smack.Roster.removeEntry(Roster.java:345)
	at saros.net.xmpp.contact.XMPPContactsService.lambda$2(XMPPContactsService.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

[This should be fixed with Smack >= 4.2.1](https://discourse.igniterealtime.org/t/smack-4-2-0-sends-ask-attribute-in-roster-removeentry-not-allowed-by-rfc6121/73403)

**Comment by stefaus** [comment]
Additional Note: Reproducibility of this Bug depends on the used XMPP-Server (Version)
