### ISSUE TITLE
JetBrains phpstorm 2021.1.2 session start issue

### ISSUE THREAD

**Issue by Igzak** [saros-project/saros#1143]
**Describe the bug**
JetBrains phpstorm 2021.1.2 show error when trying to start saros project sharing with other person, looks like method called by plugin not exist in phpstorm ide

**To Reproduce**
1. Install phpstorm 2021.1.2
2. Try start session with someone

**Expected behavior**
Session started without any troubles

**Log files**

Can`t share 😥

**Screenshots**
![issue_saros](https://user-images.githubusercontent.com/22889464/119967443-07749a00-bfb5-11eb-89ec-3418923019d2.png)

**Environment (please complete the following information):**
 - OS:  Windows 10 [20H2]
 - IDE phpstorm 2021.1.2
 - Saros Plugin Version [0.3.0]

**Additional context**
`java.lang.NoSuchMethodError: 'com.intellij.openapi.module.ModuleType[] com.intellij.openapi.module.ModuleTypeManager.getRegisteredTypes()'
	at saros.intellij.negotiation.hooks.ModuleTypeNegotiationHook.applyActualParameters(ModuleTypeNegotiationHook.java:150)
	at saros.negotiation.OutgoingSessionNegotiation.applySessionParameters(OutgoingSessionNegotiation.java:442)
	at saros.negotiation.OutgoingSessionNegotiation.start(OutgoingSessionNegotiation.java:182)
	at saros.core.ui.eventhandler.NegotiationHandler$OutgoingInvitationJob.run(NegotiationHandler.java:131)
	at saros.intellij.runtime.UIMonitoredJob.run(UIMonitoredJob.java:42)`

**Comment by tobous** [comment]
The current release of Saros/I (`0.3.0`) is not compatible with products based on the 2021 JetBrains platform (i.e. IntelliJ/PhpStorm `2021.X`). This issue has already been resolved on the master, but I haven't gotten around to releasing a new Saros/I version yet. Sorry for the inconvenience.

You can either wait for the next official release or try using a [development build](https://www.saros-project.org/releases/#development-builds).
