### ISSUE TITLE
[I] ClassNotFoundException while loading Saros in Jetbrains CLion IDE v2021.2

### ISSUE THREAD

**Issue by robertgroh** [saros-project/saros#1146]
**Describe the bug**
While loading the Saros Plugin in Jetbrains CLion IDE, the startup of the IDE aborts with an ClassNotFoundException and the plugin is disabled for the next start of the IDE

**To Reproduce**
1. Install Saros Dev-Build (saros-intellij-dev-a969bb9cd4) in the Jetbrains CLion IDE v2021.2 (Release Candidate build 212.4746.61)
2. Restart the IDE, after activating the plugin
3. On startup, an ClassNotFoundException is thrown, while loading saros (see the following log)

**Expected behavior**
Saros can succesfully loaded/initialized in Jetbrains CLion IDE v2021.2 (Release Candidate build 212.4746.61)

**Log files**

> INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Toml (0.2.151.3997-212), Saros (0.3.0.DEV-a969bb9cd4), Rust (0.4.151.3997-212) 
> INFO -        #com.intellij.idea.Main - WM detected: KWin 
> ERROR - llij.ide.plugins.PluginManager - com.intellij.diagnostic.PluginException: Fatal error initializing '
>         saros.intellij.SarosComponent
>       ' [Plugin: saros] 
> java.util.concurrent.CompletionException: com.intellij.diagnostic.PluginException: Fatal error initializing '
>         saros.intellij.SarosComponent
>       ' [Plugin: saros]
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
> 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
> 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
> 	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
> 	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
> 	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
> 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> Caused by: com.intellij.diagnostic.PluginException: Fatal error initializing '
>         saros.intellij.SarosComponent
>       ' [Plugin: saros]
> 	at com.intellij.serviceContainer.ComponentManagerImpl.handleInitComponentError$intellij_platform_serviceContainer(ComponentManagerImpl.kt:515)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:387)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
> 	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
> 	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
> 	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
> 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
> 	... 11 more
> Caused by: java.lang.ClassNotFoundException: 
>         saros.intellij.SarosComponent
>        PluginClassLoader(plugin=PluginDescriptor(name=Saros, id=saros, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.4746.61.plugins/saros-intellij, version=0.3.0.DEV-a969bb9cd4, package=null), packagePrefix=null, instanceId=59, state=active)
> 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
> 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
> 	... 17 more
> 	
> ERROR - llij.ide.plugins.PluginManager - CLion 2021.2  Build #CL-212.4746.61 
> ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
> ERROR - llij.ide.plugins.PluginManager - OS: Linux 
> ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Saros version: 0.3.0.DEV-a969bb9cd4 
> INFO - e.plugins.DisabledPluginsState - Plugins to disable: [saros] 
> INFO -  
> INFO - Plugin Error 
> INFO - Plugin 'saros' failed to initialize and will be disabled. Please restart CLion. 
> INFO -  
> INFO - java.lang.ClassNotFoundException:  
> 	         saros.intellij.SarosComponent 
> 	        PluginClassLoader(plugin=PluginDescriptor(name=Saros, id=saros, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/CLion/ch-1/212.4746.61.plugins/saros-intellij, version=0.3.0.DEV-a969bb9cd4, package=null), packagePrefix=null, instanceId=59, state=active) 
> 	 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254) 
> 	 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) 
> 	 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441) 
> 	 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380) 
> 	 	at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58) 
> 	 	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255) 
> 	 	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63) 
> 	 	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77) 
> 	 	at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt) 
> 	 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) 
> 	 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) 
> 	 	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) 
> 	 	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75) 
> 	 	at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt) 
> 	 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) 
> 	 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) 
> 	 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) 
> 	 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) 
> 	 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) 
> 	 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) 
> 	 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (JDK: 11.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.)
 - IDE: Jetbrains CLion IDE v2021.2 (Release Candidate build 212.4746.61)
   but also reproducible with the latest EAP build (no subscription or triale period required): [2021.2 Beta build 212.4746.15](https://confluence.jetbrains.com/pages/viewpage.action?pageId=222265550)
    (to download the EAP build, **scroll to** the version *2021.2 Beta build 212.4746.15* on the [CLion EAP Page](https://www.jetbrains.com/clion/nextversion/)) 
 - Saros Version: saros-intellij-dev-a969bb9cd4 ([Dev/Master-Build](https://github.com/saros-project/saros/actions/runs/686315728))

**Comment by gamma-02** [comment]
Getting the same issue. Downgrading Intellij to the latest 2020 version fixed it.

**Comment by lowdev** [comment]
@tobous, i Tried to update intellijVersion to "2021.2.2"
and plugin.xml idea-version since-build

but we still have the same issue...

Do you have any clue how to make it compatible ?

**Comment by KevinStarWars** [comment]
We're having the same problem on this build: 
IntelliJ IDEA 2021.3.2 (Ultimate Edition) 
Build #IU-213.6777.52, built on January 28, 2022 

Can you please review this issue?
