### ISSUE TITLE
File rename and follow mode -> error message

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#13]
When a file is renamed by the host/driver, a new entry appears in the Error Log View of observers, but only in follow mode.No popup or anything, just the silent entry:

```
EditorAPI cannot open file which does not exist: L/<path containing the old file name> (EditorAPI.java:187)
StackTrace:
    at de.fu_berlin.inf.dpp.editor.internal.EditorAPI.openEditor(EditorAPI.java:188)
    at de.fu_berlin.inf.dpp.editor.EditorManager.jumpToUser(EditorManager.java:1630)
    at de.fu_berlin.inf.dpp.editor.EditorManager.setFollowing(EditorManager.java:1545)
    at de.fu_berlin.inf.dpp.editor.EditorManager.partInputChanged(EditorManager.java:1036)
    at de.fu_berlin.inf.dpp.editor.internal.EditorPartListener.partInputChanged(EditorPartListener.java:82)
    at de.fu_berlin.inf.dpp.editor.internal.SafePartListener2$6.run(SafePartListener2.java:79)
    at de.fu_berlin.inf.dpp.util.Util$6.run(Util.java:417)
    at de.fu_berlin.inf.dpp.util.Util.runSafeSync(Util.java:533)
    at de.fu_berlin.inf.dpp.editor.internal.SafePartListener2.partInputChanged(SafePartListener2.java:77)
    at org.eclipse.ui.internal.PartListenerList2$8.run(PartListenerList2.java:193)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.runtime.Platform.run(Platform.java:888)
    at org.eclipse.ui.internal.PartListenerList2.fireEvent(PartListenerList2.java:55)
    at org.eclipse.ui.internal.PartListenerList2.firePartInputChanged(PartListenerList2.java:191)
    at org.eclipse.ui.internal.PartService.firePartInputChanged(PartService.java:265)
    at org.eclipse.ui.internal.WWinPartService$WWinListener.partInputChanged(WWinPartService.java:66)
    at org.eclipse.ui.internal.PartListenerList2$8.run(PartListenerList2.java:193)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.runtime.Platform.run(Platform.java:888)
    at org.eclipse.ui.internal.PartListenerList2.fireEvent(PartListenerList2.java:55)
    at org.eclipse.ui.internal.PartListenerList2.firePartInputChanged(PartListenerList2.java:191)
    at org.eclipse.ui.internal.PartService.firePartInputChanged(PartService.java:265)
    at org.eclipse.ui.internal.WorkbenchPagePartList.firePartInputChanged(WorkbenchPagePartList.java:72)
    at org.eclipse.ui.internal.PartList.partInputChanged(PartList.java:195)
    at org.eclipse.ui.internal.PartList.access$4(PartList.java:194)
    at org.eclipse.ui.internal.PartList$1.propertyChanged(PartList.java:54)
    at org.eclipse.ui.internal.WorkbenchPartReference.fireInternalPropertyChange(WorkbenchPartReference.java:375)
    at org.eclipse.ui.internal.WorkbenchPartReference.immediateFirePropertyChange(WorkbenchPartReference.java:574)
    at org.eclipse.ui.internal.WorkbenchPartReference.firePropertyChange(WorkbenchPartReference.java:564)
    at org.eclipse.ui.internal.WorkbenchPartReference.partPropertyChanged(WorkbenchPartReference.java:299)
    at org.eclipse.ui.internal.EditorReference.partPropertyChanged(EditorReference.java:498)
    at org.eclipse.ui.internal.WorkbenchPartReference$2.propertyChanged(WorkbenchPartReference.java:181)
    at org.eclipse.ui.part.WorkbenchPart.firePropertyChange(WorkbenchPart.java:129)
    at org.eclipse.ui.texteditor.AbstractTextEditor.firePropertyChange(AbstractTextEditor.java:6245)
    at org.eclipse.ui.texteditor.AbstractTextEditor.setInputWithNotify(AbstractTextEditor.java:4207)
    at org.eclipse.ui.texteditor.AbstractTextEditor.setInput(AbstractTextEditor.java:4221)
    at org.eclipse.ui.texteditor.AbstractTextEditor$7.run(AbstractTextEditor.java:534)
    at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener.execute(AbstractTextEditor.java:603)
    at org.eclipse.ui.texteditor.AbstractTextEditor$ElementStateListener.elementMoved(AbstractTextEditor.java:564)
    at org.eclipse.ui.editors.text.TextFileDocumentProvider$FileBufferListener.underlyingFileMoved(TextFileDocumentProvider.java:322)
    at org.eclipse.core.internal.filebuffers.TextFileBufferManager$6.run(TextFileBufferManager.java:743)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.filebuffers.TextFileBufferManager.fireUnderlyingFileMoved(TextFileBufferManager.java:741)
    at org.eclipse.core.internal.filebuffers.ResourceFileBuffer.handleFileMoved(ResourceFileBuffer.java:463)
    at org.eclipse.core.internal.filebuffers.ResourceFileBuffer$3.execute(ResourceFileBuffer.java:162)
    at org.eclipse.core.internal.filebuffers.ResourceFileBuffer$SafeFileChange.run(ResourceFileBuffer.java:86)
    at org.eclipse.ui.internal.editors.text.UISynchronizationContext.run(UISynchronizationContext.java:34)
    at org.eclipse.core.internal.filebuffers.TextFileBufferManager.execute(TextFileBufferManager.java:630)
    at org.eclipse.core.internal.filebuffers.ResourceFileBuffer$FileSynchronizer.resourceChanged(ResourceFileBuffer.java:180)
    at org.eclipse.core.internal.events.NotificationManager$2.run(NotificationManager.java:291)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
    at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
    at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:313)
    at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1022)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:1809)
    at de.fu_berlin.inf.dpp.util.FileUtil.move(FileUtil.java:457)
    at de.fu_berlin.inf.dpp.project.SharedResourcesManager.exec(SharedResourcesManager.java:641)
    at de.fu_berlin.inf.dpp.project.SharedResourcesManager.exec(SharedResourcesManager.java:588)
    at de.fu_berlin.inf.dpp.project.internal.SharedProject$5.run(SharedProject.java:582)
    at de.fu_berlin.inf.dpp.util.Util$6.run(Util.java:417)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:134)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3885)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3506)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2405)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2369)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2221)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:500)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:493)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:113)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:194)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:559)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:514)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1311)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1287)
```

Reported by: ahaferburg

Original Ticket: [dpp/bugs/396](https://sourceforge.net/p/dpp/bugs/396)

**Comment by srossbach** [comment]
See #10
