### ISSUE TITLE
Whiteboard DH: Text tool broken

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#48]
Problem description
===================

When you try to create text objects using the text tool, exceptions are thrown, no text is drawn and the other tools cease to work properly. If you close the Whiteboard and try to reopen it, it displays errors.

To reproduce
============

1. Draw something with the freehand tool to make sure normal tools work.
2. Select the text tool and click on the canvas. A dialog for text input opens.
3. Type some text. Hit Enter. The cursor turns into a cross until you move it again. The first exception of those reproduced below is thrown and no text is drawn.
4. Try to draw with the freehand tool, again. The line you draw vanishes as soon as you release the mouse button. The second exception from below is thrown.
5. Close the Whiteboard. An error occurs. 
6. Reopen the Whiteboard through Show View. Another error occurs. The exceptions are the same as before.

Exceptions
==========

Upon entering text
------------------

```
ERROR 09:38:13,514 [main] (SXEController.java:475) Could not apply local command because of an error:
java.lang.NumberFormatException: For input string: "hallo"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Byte.parseByte(Byte.java:148)
        at java.lang.Byte.parseByte(Byte.java:174)
        at de.fu_berlin.inf.dpp.whiteboard.gef.model.SVGTextBoxRecord.getText(SVGTextBoxRecord.java:41)
        at de.fu_berlin.inf.dpp.whiteboard.gef.editpart.SVGTextBoxPart.createFigure(SVGTextBoxPart.java:53)
        at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getFigure(AbstractGraphicalEditPart.java:494)
        at de.fu_berlin.inf.dpp.whiteboard.gef.editpart.ElementRecordPart.getFigure(ElementRecordPart.java:109)
        at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addChildVisual(AbstractGraphicalEditPart.java:208)
        at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:211)
        at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:781)
        at de.fu_berlin.inf.dpp.whiteboard.gef.editpart.ElementRecordPart.childElementRecordChanged(ElementRecordPart.java:72)
        at de.fu_berlin.inf.dpp.whiteboard.sxe.records.ChildRecordChangeCache.notifyListeners(ChildRecordChangeCache.java:166)
        at de.fu_berlin.inf.dpp.whiteboard.sxe.AbstractSXEMessageHandler.notifyLocalListeners(AbstractSXEMessageHandler.java:99)
        at de.fu_berlin.inf.dpp.whiteboard.sxe.SXEController.executeAndCommit(SXEController.java:463)
        at de.fu_berlin.inf.dpp.whiteboard.gef.commands.SXECommand.execute(SXECommand.java:38)
        at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:199)
        at de.fu_berlin.inf.dpp.whiteboard.gef.editor.SXECommandStack.execute(SXECommandStack.java:26)
        at org.eclipse.gef.tools.AbstractTool.executeCommand(AbstractTool.java:425)
        at org.eclipse.gef.tools.AbstractTool.executeCurrentCommand(AbstractTool.java:438)
        at de.fu_berlin.inf.dpp.whiteboard.gef.tools.CreationToolWithoutSelection.performCreation(CreationToolWithoutSelection.java:28)
        at de.fu_berlin.inf.dpp.whiteboard.gef.tools.TextboxCreationTool.performCreation(TextboxCreationTool.java:119)
        at org.eclipse.gef.tools.CreationTool.handleButtonUp(CreationTool.java:189)
        at org.eclipse.gef.tools.AbstractTool.mouseUp(AbstractTool.java:1200)
        at org.eclipse.gef.EditDomain.mouseUp(EditDomain.java:301)
        at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseReleased(DomainEventDispatcher.java:380)
        at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseUp(LightweightSystem.java:548)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:219)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3588)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3209)
        at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
        at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
        at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
```

Upon drawing with the freehand tool
-----------------------------------

```
ERROR 09:42:29,403 [main] (SXEController.java:475) Could not apply local command because of an error:
java.lang.IndexOutOfBoundsException: Index does not exist
        at org.eclipse.draw2d.Figure.add(Figure.java:139)
        at org.eclipse.draw2d.FreeformLayer.add(FreeformLayer.java:28)
        at org.eclipse.draw2d.Figure.add(Figure.java:184)
        at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addChildVisual(AbstractGraphicalEditPart.java:209)
        at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:211)
        at org.eclipse.gef.editparts.AbstractEditPart.refreshChildren(AbstractEditPart.java:781)
        at de.fu_berlin.inf.dpp.whiteboard.gef.editpart.ElementRecordPart.childElementRecordChanged(ElementRecordPart.java:72)
        at de.fu_berlin.inf.dpp.whiteboard.sxe.records.ChildRecordChangeCache.notifyListeners(ChildRecordChangeCache.java:166)
        at de.fu_berlin.inf.dpp.whiteboard.sxe.AbstractSXEMessageHandler.notifyLocalListeners(AbstractSXEMessageHandler.java:99)
        at de.fu_berlin.inf.dpp.whiteboard.sxe.SXEController.executeAndCommit(SXEController.java:463)
        at de.fu_berlin.inf.dpp.whiteboard.gef.commands.SXECommand.execute(SXECommand.java:38)
        at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:199)
        at de.fu_berlin.inf.dpp.whiteboard.gef.editor.SXECommandStack.execute(SXECommandStack.java:26)
        at org.eclipse.gef.tools.AbstractTool.executeCommand(AbstractTool.java:425)
        at org.eclipse.gef.tools.AbstractTool.executeCurrentCommand(AbstractTool.java:438)
        at de.fu_berlin.inf.dpp.whiteboard.gef.tools.CreationToolWithoutSelection.performCreation(CreationToolWithoutSelection.java:28)
        at org.eclipse.gef.tools.CreationTool.handleButtonUp(CreationTool.java:189)
        at org.eclipse.gef.tools.AbstractTool.mouseMove(AbstractTool.java:1159)
        at org.eclipse.gef.EditDomain.mouseMove(EditDomain.java:287)
        at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchMouseMoved(DomainEventDispatcher.java:365)
        at org.eclipse.draw2d.LightweightSystem$EventHandler.mouseMove(LightweightSystem.java:543)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:211)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3588)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3209)
        at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
        at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
        at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
```

Insights
========

The exceptions provide quite a good hint on where the problem lies. In Whiteboard DH, <code>SVGTextBoxRecord.getText()</code> was changed and probably with this the error was introduced.

Reported by: rmoehn

Original Ticket: [dpp/bugs/813](https://sourceforge.net/p/dpp/bugs/813)

**Comment by AbdBarho** [comment]
the work of Hendrik Degner never got fully integrated in the whiteboard, the current available text input tool does not have this problem.
