### ISSUE TITLE
Eclipse test SarosSessionTest.testCreateSarosSession runs into assertion error

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#497]
The test `testCreateSarosSession()` in eclipse/test/junit/saros/session/internal/SarosSessionTest.java runs into an assertion error. Weirdly, this does not cause the test case to fail. 

Stacktrace:
```
Internal Fatal Error:
java.lang.AssertionError: 
  Unexpected method call EditorManager.getOpenEditors():
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:85)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:94)
	at saros.editor.EditorManager$$EnhancerByCGLIB$$5a0a8f13.getOpenEditors(<generated>)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer.calculateChecksums(ConsistencyWatchdogServer.java:205)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer.access$200(ConsistencyWatchdogServer.java:38)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer$1$1.run(ConsistencyWatchdogServer.java:77)
	at saros.util.ThreadUtils$1.run(ThreadUtils.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Original caller:
StackTrace:
	at saros.util.ThreadUtils.wrapSafe(ThreadUtils.java:29)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer$1.run(ConsistencyWatchdogServer.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

<details>
<summary>Complete test execution log:</summary>

```
> Task :saros.eclipse:test
could not install listener, unsupported interface
Registering new converter of class saros.misc.xstream.SPathConverter
Registering new converter of class saros.misc.xstream.UserConverter
activity dispatcher started
Internal Fatal Error:
java.lang.AssertionError: 
  Unexpected method call EditorManager.getOpenEditors():
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:85)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:94)
	at saros.editor.EditorManager$$EnhancerByCGLIB$$5a0a8f13.getOpenEditors(<generated>)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer.calculateChecksums(ConsistencyWatchdogServer.java:205)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer.access$200(ConsistencyWatchdogServer.java:38)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer$1$1.run(ConsistencyWatchdogServer.java:77)
	at saros.util.ThreadUtils$1.run(ThreadUtils.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Original caller:
StackTrace:
	at saros.util.ThreadUtils.wrapSafe(ThreadUtils.java:29)
	at saros.concurrent.watchdog.ConsistencyWatchdogServer$1.run(ConsistencyWatchdogServer.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
activity dispatcher stopped
Unregistering (resetting) converter of class saros.misc.xstream.UserConverter
Unregistering (resetting) converter of class saros.misc.xstream.SPathConverter
Session lasted 0 min 0 s
deleting existing port mappings
saros.session.internal.SarosSessionTest > testCreateSarosSession PASSED
```

</details>

**Comment by srossbach** [comment]
Because the exception is thrown in a Worker thread and not in the JUnit thread, Actually this is not nice but also not a bug because the test is not testing the behaviour of the Watchdog.

**Comment by tobous** [comment]
I created and added the test case to denote that it is a problem with a test case and not the software itself. 

But I still would classify this as a bug in the testing logic. The assertion error is thrown by EasyMock, which probably means that there is an issue with the stubbing of the test setup.

**Comment by srossbach** [comment]
The used mock does not really setup anything: https://github.com/saros-project/saros/blob/master/eclipse/test/junit/saros/test/mocks/EditorManagerMock.java#L9
