### ISSUE TITLE
Heartbeat introduced in #397 causes vectortime desync

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#580]
**Describe the bug**
The vector time desyncs during the running session, independently of whether the users actively create activities or not. This leads to the participants no longer being able to send editor activities after some time, thereby breaking the session.

This behavior can be replicated with both Saros/I and Saros/E.

The issue starts with the commit 11f3931aed7c03ed828c9e1286308eb37e69a99c (it can't be replicated on prior commits), which makes it almost guaranteed that this behavior is caused by the heartbeat patch introduced in #397.

**To Reproduce**
1. Start a Saros session. (You can also edit some files to ensure that the session is working at this point.)
2. Wait for some time to ensure a heartbeat activity was send (at least one minute).
3. Type something in a shared editor.

**Expected behavior**
The editor activities (text edits) should be transferred to the other participants. Instead, nothing happens as the activity transformation fails with an exception.

```
ERROR 16:28:57,837 [DispatchContext] (ConcurrentDocumentServer.java:138) failed to transform jupiter activity: JupiterActivity(timestamp: [5,4], operation: Insert(1622,'a',1622), source: intellij_test_1@saros-con.imp.fu-berlin.de/Saros)
saros.concurrent.jupiter.TransformationException: Precondition #3 violated (Vector time does not match): [5,4] , [4,4]
	at saros.concurrent.jupiter.internal.Jupiter.checkPreconditions(Jupiter.java:268)
	at saros.concurrent.jupiter.internal.Jupiter.receiveJupiterActivity(Jupiter.java:158)
	at saros.concurrent.jupiter.internal.JupiterDocumentServer.transformJupiterActivity(JupiterDocumentServer.java:65)
	at saros.concurrent.management.JupiterServer.transform(JupiterServer.java:104)
	at saros.concurrent.management.ConcurrentDocumentServer.receive(ConcurrentDocumentServer.java:136)
	at saros.concurrent.management.ConcurrentDocumentServer.transformIncoming(ConcurrentDocumentServer.java:112)
	at saros.session.internal.ActivityHandler.directServerActivities(ActivityHandler.java:386)
	at saros.session.internal.ActivityHandler.handleIncomingActivities(ActivityHandler.java:136)
	at saros.session.internal.SarosSession.exec(SarosSession.java:721)
	at saros.session.internal.ActivitySequencer$3.run(ActivitySequencer.java:362)
	at saros.util.ThreadUtils$1.run(ThreadUtils.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Environment (please complete the following information):**
 - OS: Archlinux, Kernel 5.1.15
 - IDE: Eclipse 2018-12 M2, IntelliJ IDEA 2018.3.4
 - Saros Version: master after 11f3931aed7c03ed828c9e1286308eb37e69a99c

**Comment by Drakulix** [comment]
@tobous That log is from the session host, right?

Because the exception happens inside the `ConcurrentDocumentServer`, the clients seem to have a higher VectrorTime then the server.
Which is pretty weird, because all my PR was doing was [calling `generateJupiterActivity`](https://github.com/saros-project/saros/pull/397/files#diff-c8f42f3ca2fd37c1945fb733fcf7b3fbR58), which [does increase the local count](https://github.com/saros-project/saros/blob/b55aad218d78217a01801150e2c21598e0fc5428/core/src/saros/concurrent/jupiter/internal/Jupiter.java#L89).

How the client ends up with a higher count is quite the mystery for me, but I am investigating.

**Comment by srossbach** [comment]
All I can say is: RTFM !

If you do not register the producer you can call fireActivity over and over again.

https://github.com/saros-project/saros/blob/master/core/src/saros/session/AbstractActivityProducer.java#L11

Somehow it did not noticed it during the review as writing my last producer was a while back.
