### ISSUE TITLE
Opening a non-text-editor for shared resources leads to user-visible error

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#711]
Trying to open a shared resource that uses a non-text-editor (like images) leads to user-visible errors (see stacktrace below) in the IDE.

This is due to the result of the call to obtain an `Editor` object never being checked, even though it can be `null`. The tagging of the corresponding method `ProjectAPI.openEditor(...)` should be adjusted as well as it is not tagged `@Nullable`.

```Java
2019-09-28 14:18:39,413 [ 127210]  ERROR - .impl.MessageBusConnectionImpl - Argument for @NotNull parameter 'editor' of saros/intellij/editor/EditorPool.add must not be null 
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'editor' of saros/intellij/editor/EditorPool.add must not be null
	at saros.intellij.editor.EditorPool.$$$reportNull$$$0(EditorPool.java)
	at saros.intellij.editor.EditorPool.add(EditorPool.java)
	at saros.intellij.editor.LocalEditorHandler.openEditor(LocalEditorHandler.java:137)
	at saros.intellij.editor.LocalEditorHandler.openEditor(LocalEditorHandler.java:69)
	at saros.intellij.eventhandler.editor.editorstate.AnnotationUpdater.setUpOpenedEditor(AnnotationUpdater.java:69)
	at saros.intellij.eventhandler.editor.editorstate.AnnotationUpdater.access$000(AnnotationUpdater.java:21)
	at saros.intellij.eventhandler.editor.editorstate.AnnotationUpdater$1.fileOpened(AnnotationUpdater.java:33)
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:102)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:446)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:370)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:242)
	at com.sun.proxy.$Proxy62.commandStarted(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandStarted(CoreCommandProcessor.java:413)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditor(FileEditorManagerImpl.java:1135)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.doOpenTextEditor(FileEditorManagerImpl.java:1216)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openTextEditor(FileEditorManagerImpl.java:1197)
	at saros.intellij.editor.ProjectAPI.lambda$openEditor$0(ProjectAPI.java:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:918)
	at saros.intellij.filesystem.Filesystem.runReadAction(Filesystem.java:100)
	at saros.intellij.editor.ProjectAPI.openEditor(ProjectAPI.java:58)
	at saros.intellij.editor.LocalEditorHandler.openEditor(LocalEditorHandler.java:135)
	at saros.intellij.editor.LocalEditorHandler.openEditor(LocalEditorHandler.java:69)
	at saros.intellij.eventhandler.editor.editorstate.PreexistingSelectionDispatcher.sendExistingSelection(PreexistingSelectionDispatcher.java:62)
	at saros.intellij.eventhandler.editor.editorstate.PreexistingSelectionDispatcher.access$000(PreexistingSelectionDispatcher.java:25)
	at saros.intellij.eventhandler.editor.editorstate.PreexistingSelectionDispatcher$1.fileOpened(PreexistingSelectionDispatcher.java:37)
	at jdk.internal.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:102)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:446)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$1(MessageBusImpl.java:242)
	at com.sun.proxy.$Proxy104.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4Edt$8(FileEditorManagerImpl.java:979)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1051)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:170)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2458)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:167)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:119)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:161)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:167)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$null$2(FocusManagerImpl.java:175)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

#### Solution approach
To solve this issue, we could simply ignore such editors.

A better approach would be to move away from always using `Editor` objects to represent open Editors as they only represent text editors. Instead, we can use `FileEditor` as these editors can represent any type of editor.

To also access the normal text editor, we could try whether it is a `TextEditor`, cast, and then use `TextEditor.getEditor()`. However, this feels more like a workaround. Will search for a cleaner solution.

**Comment by tobous** [comment]
Update: The method `FileEditorManager.openTextEditor(...)` still opens the editor, even if it is not a text editor. Therefore, we can still use it. As we don't really care about anything other than text editors, the current editor handling can remain.
