### ISSUE TITLE
Inconsistency after dirty file deletion

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#75]
Steps to reproduce:

1. Alice creates a project with a file with some content and opens that file.
2. Alice invites Bob to a Saros session, Bob joins.
3. Bob opens the only file in the project.
4. Alice closes the single file.
5. Bob starts editing: The file gets "dirty".
6. Alice deletes the file, sees an Eclipse dialog stating this file contains unsaved changes and she confirms her choice with "Continue". (Note: If she never opened the file before, she will see a different dialog that can't be "continued".)
7. From this point, Alice's log shows errors (see below, ChecksumActivities cannot be transformed)
8. Bob is asked by an Eclipse dialog whether he wants to save the file that has been removed on the harddrive. He simply clicks OK, accepting the default location and filename.
9. The file and its content reappear at Alice's side.
10. Any further changes by Bob are not applied to Alice's document; Bob's state is inconsistent.

The first error on Alice's side.
~~~
ERROR 19:21:22,114 [DispatchContext] (ConcurrentDocumentServer.java:197) failed to transform checksum activity: ChecksumActivity(path: SPath [path=file.txt, project=Foo1_Saros], hash: -203257724, length: 8, jupiterTimestamp: [0,4])
de.fu_berlin.inf.dpp.concurrent.jupiter.TransformationException: precondition #2 violated (Remote vector time (4) is greater than local vector time (0)).
	at de.fu_berlin.inf.dpp.concurrent.jupiter.internal.Jupiter.isCurrent(Jupiter.java:147)
	at de.fu_berlin.inf.dpp.concurrent.jupiter.internal.JupiterDocumentServer.withTimestamp(JupiterDocumentServer.java:131)
	at de.fu_berlin.inf.dpp.concurrent.management.JupiterServer.withTimestamp(JupiterServer.java:114)
	at de.fu_berlin.inf.dpp.concurrent.management.ConcurrentDocumentServer.withTimestamp(ConcurrentDocumentServer.java:195)
	at de.fu_berlin.inf.dpp.concurrent.management.ConcurrentDocumentServer.transformIncoming(ConcurrentDocumentServer.java:128)
	at de.fu_berlin.inf.dpp.session.internal.ActivityHandler.directServerActivities(ActivityHandler.java:422)
	at de.fu_berlin.inf.dpp.session.internal.ActivityHandler.handleIncomingActivities(ActivityHandler.java:144)
	at de.fu_berlin.inf.dpp.session.internal.SarosSession.exec(SarosSession.java:760)
	at de.fu_berlin.inf.dpp.session.internal.ActivitySequencer$3.run(ActivitySequencer.java:379)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
~~~

The second error on Alice's side:
~~~
ERROR 19:22:18,461 [main] (EditorManager.java:763) TextEditActivity refers to file which is not available locally: TextEditActivity(offset: 5, new: 'J', old: '', path: SPath [path=file.txt, project=Foo1_Saros], src: dev7_bob_stf@saros-con.imp.fu-berlin.de/Saros)
[...]
ERROR 19:23:11,937 [DispatchContext] (ConcurrentDocumentServer.java:151) failed to transform jupiter activity: JupiterActivity(timestamp: [5,0], operation: Insert(5,'J',5), source: dev7_bob_stf@saros-con.imp.fu-berlin.de/Saros)
de.fu_berlin.inf.dpp.concurrent.jupiter.TransformationException: Precondition #3 violated (Vector time does not match): [5,0] , [0,0]
	at de.fu_berlin.inf.dpp.concurrent.jupiter.internal.Jupiter.checkPreconditions(Jupiter.java:301)
	at de.fu_berlin.inf.dpp.concurrent.jupiter.internal.Jupiter.receiveJupiterActivity(Jupiter.java:174)
	at de.fu_berlin.inf.dpp.concurrent.jupiter.internal.JupiterDocumentServer.transformJupiterActivity(JupiterDocumentServer.java:73)
	at de.fu_berlin.inf.dpp.concurrent.management.JupiterServer.transform(JupiterServer.java:106)
	at de.fu_berlin.inf.dpp.concurrent.management.ConcurrentDocumentServer.receive(ConcurrentDocumentServer.java:149)
	at de.fu_berlin.inf.dpp.concurrent.management.ConcurrentDocumentServer.transformIncoming(ConcurrentDocumentServer.java:125)
	at de.fu_berlin.inf.dpp.session.internal.ActivityHandler.directServerActivities(ActivityHandler.java:422)
	at de.fu_berlin.inf.dpp.session.internal.ActivityHandler.handleIncomingActivities(ActivityHandler.java:144)
	at de.fu_berlin.inf.dpp.session.internal.SarosSession.exec(SarosSession.java:760)
	at de.fu_berlin.inf.dpp.session.internal.ActivitySequencer.executeActivities(ActivitySequencer.java:357)
	at de.fu_berlin.inf.dpp.session.internal.ActivitySequencer.receiveActivities(ActivitySequencer.java:605)
	at de.fu_berlin.inf.dpp.session.internal.ActivitySequencer.access$0(ActivitySequencer.java:566)
	at de.fu_berlin.inf.dpp.session.internal.ActivitySequencer$1.processPacket(ActivitySequencer.java:102)
	at de.fu_berlin.inf.dpp.net.internal.XMPPReceiver.forwardPacket(XMPPReceiver.java:143)
	at de.fu_berlin.inf.dpp.net.internal.XMPPReceiver.access$1(XMPPReceiver.java:132)
	at de.fu_berlin.inf.dpp.net.internal.XMPPReceiver$5.run(XMPPReceiver.java:122)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
~~~

Reported by: fzieris

Original Ticket: [dpp/bugs/878](https://sourceforge.net/p/dpp/bugs/878)

**Comment by tobous** [comment]
Issue consists of two parts. The dirty editor remaining open for Bob is fixed by #752. The jupiter vector time desync will be fixed by #714.
