### ISSUE TITLE
Sharing fail

### ISSUE THREAD

**Issue by DevTeXon** [saros-project/saros#782]
When i start to sahre a project the friend became a call and accept. Then when hes joined the session he dosent get the project download call. But i get an error.

```
java.lang.AssertionError: Encountered path that is not located below the given base directory H:\IFH\IFH_Survival - D:\IFH\IFH_Survival\src\main\java
	at saros.intellij.negotiation.ModuleUtils.getRelativeRootPath(ModuleUtils.java:36)
	at saros.intellij.negotiation.ModuleConfigurationProvider.lambda$flatten$0(ModuleConfigurationProvider.java:156)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at saros.intellij.negotiation.ModuleConfigurationProvider.flatten(ModuleConfigurationProvider.java:160)
	at saros.intellij.negotiation.ModuleConfigurationProvider.getMapping(ModuleConfigurationProvider.java:118)
	at saros.negotiation.AdditionalProjectDataFactory.build(AdditionalProjectDataFactory.java:61)
	at saros.negotiation.AbstractOutgoingProjectNegotiation.createProjectNegotiationDataList(AbstractOutgoingProjectNegotiation.java:354)
	at saros.negotiation.AbstractOutgoingProjectNegotiation.run(AbstractOutgoingProjectNegotiation.java:99)
	at saros.core.ui.eventhandler.NegotiationHandler$OutgoingProjectJob.run(NegotiationHandler.java:200)
	at saros.intellij.runtime.UIMonitoredJob.run(UIMonitoredJob.java:42)
```

 - OS: Windows 10
 - IDE Intellij 2019.3
 - Saros Version 0.2.1

**Comment by tobous** [comment]
Thanks for reporting the issue and sorry for the inconvenience. I fixed that one yesterday/today with #778.

The issue is caused by faulty parsing that led to the default drive being used to resolve the path. If you don't want to build the plugin yourself ([how to set up for building Saros locally](https://www.saros-project.org/contribute/development-environment.html), [how to build the plugin zip](https://www.saros-project.org/contribute/processes/release.html#plug-in-zip)) or wait for the next release, a workaround would be to have the project on your "default" drive. (I am not quite sure how Java/Windows determines this. Probably by looking at the user home directory. But looking at the logs, this should be drive `D:/` for you. So moving the project files to drive `D:/` should work as a temporary workaround until the next release.)
